### ISSUE TITLE
Create container tag for each selfoss version

### ISSUE THREAD

**Issue by armandabric** [JensErat/docker-selfoss#5]
Actually there is no tag https://hub.docker.com/r/jenserat/selfoss/tags/

It's nice to allow user to lock the needed version of selfoss by using the docker tag system.

**Comment by JensErat** [comment]
I agree on tags being helpful, but they seem a little bit of overburden for such a small image and minor changes applied to Selfoss. Managing multiple Git branches results in too high effort for a side project like this. As soon as I have some more time to spare, I'll try and get the Dockerfile upstream, which will result in new tags automatically derived from the selfoss releases.

**Comment by armandabric** [comment]
I'm not talking about different branch in git but create tag on docker hub after a new release. It's two command to run after the build: 

```
$ docker tag *some container id* jenserat/selfoss:v0.x
$ docker push jenserat/selfoss:v0.x
```
